const textE = document.getElementById('text');
const wordsE = document.getElementById('words');
const result = document.getElementById('result');
const includedE = document.getElementById('included');
const notIncludedE = document.getElementById('not-included');
const includedLabel = document.getElementById('included-label');
const notIncludedLabel = document.getElementById('not-included-label');
let itc = "";
let nitc = "";
let duplicates;
